#!/bin/bash

rm -rf temp
mkdir temp
cp chrome.manifest temp
cp install.rdf temp
cp icon.png temp
cp icon64.png temp
cp chrome temp -r
cp components temp -r
cp content temp -r
cp defaults temp -r
cp locale temp -r
cp skin temp -r

cd temp

#Substitute variables
while read LINE; do
    if [[ $LINE != [A-Z]* ]]; then
        continue
    fi
    LINE1=`echo $LINE | grep -oE "^[^=]+"`
    LINE2=`echo $LINE | grep -oE "[^=]+$"`
    sed "s|\$$LINE1|$LINE2|g" -i `find . -name "*.rdf"` `find . -name "*.xul"` `find . -name "*.js"` `find . -name "*.css"` `find . -name "*.manifest"`
    eval "$LINE1=\"$LINE2\""
done < "../config.txt"

cd content/sunbird

for F in calendar-doctype calendar-sets calendar-sets-extra calendar-scripts sunbird-scripts calendar-menubar sunbird-toolbar; do
    tail -n +5 "$F.inc" > "$F.inc.temp"
    sed "/#include $F.inc/r $F.inc.temp" -i calendar.xul
    sed "s/#include $F.inc//g" -i calendar.xul
    rm "$F.inc"
    rm "$F.inc.temp"
done
sed -E "s/^#.*//g" -i *
cd ../..

cd skin
cp winstripe/toolbar.css winstripe-aero
sed "s/\.png/-aero\.png/g" -i winstripe-aero/toolbar.css
cd ..

for ARG in $@; do
    if [[ $ARG == "-no-sidebar" ]]; then
        rm content/lightbird/tasksSidebar.js
        rm content/lightbird/tasksSidebar.xul
        rm content/lightbird/navigatorOverlay.xul
        OVERLAY=`grep "navigatorOverlay" chrome.manifest`
        sed -E "s|$OVERLAY||g" -i chrome.manifest
    fi
done

zip ../$NAME-$VERSION-sm.xpi * -rq
