# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

<commandset id="commands"/>

<commandset id="tasksCommands"/>

<stringbundleset id="stringbundleset">
  <stringbundle id="bundle_brand"
                src="chrome://branding/locale/brand.properties"/>
  <stringbundle id="bundle_viewApplyTheme"/>
</stringbundleset>