# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

<!-- DTD File with all strings specific to the calendar -->
<!DOCTYPE window
[
  <!ENTITY % dtd1 SYSTEM "chrome://calendar/locale/global.dtd" > %dtd1;
  <!ENTITY % dtd2 SYSTEM "chrome://calendar/locale/calendar.dtd" > %dtd2;
  <!ENTITY % sunbirdDTD SYSTEM "chrome://sunbird/locale/sunbird.dtd" > %sunbirdDTD;
  <!ENTITY % calendarMenuOverlayDTD SYSTEM "chrome://calendar/locale/menuOverlay.dtd" > %calendarMenuOverlayDTD;
  <!ENTITY % sunbirdMenuOverlayDTD SYSTEM "chrome://sunbird/locale/menuOverlay.dtd" > %sunbirdMenuOverlayDTD;
  <!ENTITY % brandDTD SYSTEM "chrome://branding/locale/brand.dtd" > %brandDTD;
  <!ENTITY % calendar-event-dialogDTD SYSTEM "chrome://calendar/locale/calendar-event-dialog.dtd" > %calendar-event-dialogDTD;
  <!ENTITY % dtd4 SYSTEM "chrome://global/locale/global.dtd" > %dtd4;
  <!ENTITY % downloadsDTD SYSTEM "chrome://communicator/locale/downloads/downloadmanager.dtd" > %downloadsDTD;
  <!ENTITY % navigatorDTD SYSTEM "chrome://navigator/locale/navigator.dtd" > %navigatorDTD;
]>
