# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

  <script type="application/javascript" src="chrome://calendar/content/calendar.js"/>
  <script type="application/javascript" src="chrome://$NAME/content/sunbird/calendar.js"/>
  <script type="application/javascript" src="chrome://$NAME/content/sunbird/calendar-offline.js"/>
  <script type="application/javascript" src="chrome://calendar/content/calendar-migration-dialog.js"/>

  <!-- NEEDED FOR APPLICATION SUPPORT -->
  <script type="application/javascript" src="chrome://$NAME/content/sunbird/applicationUtil.js"/>
  <script type="application/javascript" src="chrome://calendar/content/calApplicationUtils.js"/>
  <script type="application/javascript" src="chrome://global/content/globalOverlay.js"/>
  <script type="application/javascript" src="chrome://global/content/printUtils.js"/>

  <script type="application/javascript" src="chrome://$NAME/content/sunbird/lightning-hooks.js"/>
